name: Publish to Chromatic
author: Chroma Software, Inc.
description: "Publish your Storybook to Chromatic and run visual regression tests"
branding:
  icon: "aperture"
  color: "orange"

inputs:
  token:
    description: "Your github token"
  projectToken: 
    description: "Your chromatic project token"
  appCode: 
    description: "Deprecated, please use projectToken instead"
  buildScriptName: 
    description: "The npm script that builds your Storybook [build-storybook]"
  doNotStart: 
    description: "Do not attempt to start or build; use if your Storybook is already running"
  exec: 
    description: "Alternatively, a full command to run to start your storybook"
  scriptName: 
    description: "The npm script that starts your Storybook [storybook]"
  storybookBuildDir: 
    description: "Provide a directory with your built storybook; use if you have already built your storybook"
  storybookCa: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookCert: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookHttps: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookKey: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookPort: 
    description: "What port is your Storybook running on (auto detected from -s, if set)"
  storybookUrl: 
    description: "Storybook is already running at (external) url (implies -S)"
  preserveMissing:
    description: "Pass the baselines forward and treat all missing stories as “preserved” without re-capturing them"
  allowConsoleErrors:
    description: "Do not exit when runtime errors occur in storybook"
  autoAcceptChanges:
    description: "Automatically accept all changes in chromatic: boolean or branchname"
  exitZeroOnChanges:
    description: "Positive exit of action even when there are changes: boolean or branchname"
  exitOnceUploaded:
    description: "Exit with 0 once the built version has been sent to chromatic: boolean or branchname"

runs: 
  main: action/register.js
  using: node12
